"""Disagreement-gradient builders for self-framing and tool-role conditions.

Extends the round-5 user-role gradient (scripts/run_disagreement_gradient.py)
to two additional framings:

- ``build_prompt_self_framing_gradient``: jury responses placed in
  assistant-role turns (mirrors ``build_prompt_self_framing`` from
  ``src.prompts``).
- ``build_prompt_tool_role_gradient``: jury responses placed in the ipython
  (tool-return) turn (mirrors ``build_prompt_tool_role`` from
  ``src.prompts``).

Each builder supports the full 0-wrong/1-wrong/2-wrong/3-wrong gradient by
taking ``wrong_agents`` (a list of jury agent keys that argue for the wrong
answer). The remaining agents argue for the correct answer, drawn from the
correct-argument corpus generated by
``scripts/run_disagreement_gradient.py``.

Per-question agent assignments come from ``make_gradient_assignments(seed=42)``
which replays the same ``random.Random(42)`` schedule as the round-5
user-role gradient so the 1v2/2v1 assignments are identical across framings.
"""
from __future__ import annotations

import random
from typing import Any

from .config import CHOICES
from .prompts import format_question


JURY_ORDER = ["gemma", "qwen", "mistral"]
JURY_DISPLAY = {
    "gemma": "Gemma-2-9B",
    "qwen": "Qwen-2.5-7B",
    "mistral": "Mistral-7B",
}


def _neutral_system() -> dict[str, str]:
    return {"role": "system", "content": "You are a helpful assistant."}


# ── Closing-line templates per gradient point (letters are substituted in)
CLOSING_TEMPLATES: dict[str, str] = {
    "0v3": "All three models agree the answer is {cor_l}.",
    "1v2": "Two of the three models say the answer is {cor_l}; one says {wrg_l}.",
    "2v1": "Two of the three models say the answer is {wrg_l}; one says {cor_l}.",
    "3v0": "All three models agree the answer is {wrg_l}.",
}

GRADIENT_POINTS = ["0v3", "1v2", "2v1", "3v0"]

N_WRONG_FOR = {"0v3": 0, "1v2": 1, "2v1": 2, "3v0": 3}


# ── Per-framing action phrases that immediately follow the closing line
SELF_ACTION_PHRASE = " Now, what is your answer?"
TOOL_ACTION_PHRASE = " Based on their analysis, what is your answer?"


def make_gradient_assignments(n_questions: int, seed: int = 42) -> dict:
    """Per-question (wrong_agents, correct_agents) lists for each gradient point.

    Replays the exact schedule used in ``scripts/run_disagreement_gradient.py``
    so the 1v2 and 2v1 agent assignments are identical across framings.
    """
    rng = random.Random(seed)
    assignments: dict[str, list[tuple[list[str], list[str]]]] = {}

    assignments["0v3"] = [([], JURY_ORDER[:]) for _ in range(n_questions)]

    grad_1v2: list[tuple[list[str], list[str]]] = []
    for _ in range(n_questions):
        agents = JURY_ORDER[:]
        rng.shuffle(agents)
        grad_1v2.append(([agents[0]], [agents[1], agents[2]]))
    assignments["1v2"] = grad_1v2

    grad_2v1: list[tuple[list[str], list[str]]] = []
    for _ in range(n_questions):
        agents = JURY_ORDER[:]
        rng.shuffle(agents)
        grad_2v1.append(([agents[0], agents[1]], [agents[2]]))
    assignments["2v1"] = grad_2v1

    assignments["3v0"] = [(JURY_ORDER[:], []) for _ in range(n_questions)]

    return assignments


def _collect_agent_lines(
    q_idx: int,
    wrg_l: str,
    cor_l: str,
    wrong_jury: dict,
    correct_jury: dict,
    wrong_agents: list[str],
) -> list[tuple[str, str, str]]:
    """Return (display_name, claimed_letter, response_text) for each jury agent
    in fixed display order (Gemma, Qwen, Mistral)."""
    out: list[tuple[str, str, str]] = []
    for agent_key in JURY_ORDER:
        display = JURY_DISPLAY[agent_key]
        if agent_key in wrong_agents:
            resp = wrong_jury[agent_key][q_idx]["response"]
            letter = wrg_l
        else:
            resp = correct_jury[agent_key][q_idx]["response"]
            letter = cor_l
        out.append((display, letter, resp))
    return out


def build_prompt_self_framing_gradient(
    q_idx: int,
    item: dict,
    wrong_idx: int,
    wrong_jury: dict,
    correct_jury: dict,
    tokenizer,
    wrong_agents: list[str],
    n_wrong: int,  # noqa: ARG001 — kept for signature symmetry / docs
    closing_tmpl: str,
    system_prompt: str | None = None,
    add_suffix: bool = True,
) -> str:
    """Self-framing gradient prompt — jury responses placed in assistant turns.

    Structurally identical to ``src.prompts.build_prompt_self_framing`` with
    the same assistant-role placement and interleaved user "Here is another
    model's analysis:" / "And a third model's view:" scaffolding.
    """
    q, opts = item["question"], item["choices"]
    correct_idx = item["answer"]
    wrg_l = CHOICES[wrong_idx]
    cor_l = CHOICES[correct_idx]

    question_text = format_question(q, opts) + "Please provide the correct answer."
    agent_lines = _collect_agent_lines(
        q_idx, wrg_l, cor_l, wrong_jury, correct_jury, wrong_agents
    )

    closing_line = closing_tmpl.format(wrg_l=wrg_l, cor_l=cor_l)
    final_user = closing_line + SELF_ACTION_PHRASE

    system_msg = (
        {"role": "system", "content": system_prompt}
        if system_prompt is not None
        else _neutral_system()
    )

    a0, a1, a2 = agent_lines
    messages: list[dict[str, Any]] = [
        system_msg,
        {"role": "user", "content": question_text},
        {"role": "assistant", "content": f"[{a0[0]}]: The answer is {a0[1]}. {a0[2]}"},
        {"role": "user", "content": "Here is another model's analysis:"},
        {"role": "assistant", "content": f"[{a1[0]}]: The answer is {a1[1]}. {a1[2]}"},
        {"role": "user", "content": "And a third model's view:"},
        {"role": "assistant", "content": f"[{a2[0]}]: The answer is {a2[1]}. {a2[2]}"},
        {"role": "user", "content": final_user},
    ]
    prompt = tokenizer.apply_chat_template(
        messages, tokenize=False, add_generation_prompt=True
    )
    if add_suffix:
        prompt += "The correct answer is ("
    return prompt


def build_prompt_tool_role_gradient(
    q_idx: int,
    item: dict,
    wrong_idx: int,
    wrong_jury: dict,
    correct_jury: dict,
    tokenizer,  # noqa: ARG001 — tool-role uses hardcoded Llama tokens, not template
    wrong_agents: list[str],
    n_wrong: int,  # noqa: ARG001
    closing_tmpl: str,
    system_prompt: str | None = None,
    add_suffix: bool = True,
) -> str:
    """Tool-role gradient prompt — jury responses placed in the ipython turn.

    Structurally identical to ``src.prompts.build_prompt_tool_role`` with the
    same ``<|python_tag|>query_ai_panel()`` pattern followed by the jury
    responses in an ``ipython``-role turn.
    """
    q, opts = item["question"], item["choices"]
    correct_idx = item["answer"]
    wrg_l = CHOICES[wrong_idx]
    cor_l = CHOICES[correct_idx]

    question_text = format_question(q, opts) + "Please provide the correct answer."
    agent_lines = _collect_agent_lines(
        q_idx, wrg_l, cor_l, wrong_jury, correct_jury, wrong_agents
    )
    tool_content = "\n\n".join(
        f"[{disp}]: The answer is {lett}. {txt}" for disp, lett, txt in agent_lines
    )

    closing_line = closing_tmpl.format(wrg_l=wrg_l, cor_l=cor_l)
    final_user = closing_line + TOOL_ACTION_PHRASE

    sys_prompt = (
        system_prompt if system_prompt is not None else "You are a helpful assistant."
    )

    prompt = (
        f"<|begin_of_text|>"
        f"<|start_header_id|>system<|end_header_id|>\n\n"
        f"{sys_prompt}<|eot_id|>"
        f"<|start_header_id|>user<|end_header_id|>\n\n"
        f"{question_text}<|eot_id|>"
        f"<|start_header_id|>assistant<|end_header_id|>\n\n"
        f"I'll query the AI panel for their views on this question.\n\n"
        f"<|python_tag|>query_ai_panel()<|eot_id|>"
        f"<|start_header_id|>ipython<|end_header_id|>\n\n"
        f"{tool_content}<|eot_id|>"
        f"<|start_header_id|>user<|end_header_id|>\n\n"
        f"{final_user}<|eot_id|>"
        f"<|start_header_id|>assistant<|end_header_id|>\n\n"
    )
    if add_suffix:
        prompt += "The correct answer is ("
    return prompt
